apiVersion: v1
kind: Namespace
metadata:
  name: APP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP
  namespace: APP
spec:
  selector:
    matchLabels:
      run: APP
  template:
    metadata:
      labels:
        run: APP
    spec:
      containers:
      - image: jeatest00000002/APP:VERSION
        name: APP
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: APP-svc
  namespace: APP
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: APP
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: APP-ingress
  namespace: APP
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "APP-static-ip"
spec:
  backend:
    serviceName: APP-svc
    servicePort: 8080
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: APP-svc
#            port:
#              number: 8080

